---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: oracle-bindable
  namespace: default
spec:
  serviceAccountName: oracle-resources-reader
  inputResources:
    - name: xedb
      ref:
        apiVersion: database.oracle.com/v1alpha1
        kind: SingleInstanceDatabase
        name: xedb-sample
  template:
    metadata:
      labels:
        app.kubernetes.io/component: xedb-sample
        app.kubernetes.io/instance: "xedb-user-secret"
        services.apps.tanzu.vmware.com/class: xedb-oracle
    type: Opaque
    stringData:
      type: oracle
      ## Specify Tanzu User info and connection string
      jdbc-url: "jdbc:oracle:thin:@xedb-sample.default:1521/$(.xedb.spec.pdbName)"
      username: tanzu
      password: TAPt3st!
