---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oracle-resources-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oracle-resources-reading
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - database.oracle.com
    resources:
      - singleinstancedatabases
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oracle-resources-reader-to-read
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oracle-resources-reading
subjects:
  - kind: ServiceAccount
    name: oracle-resources-reader
    namespace: default
