---
apiVersion: v1
kind: Secret
metadata:
  name: xedb-admin-secret
  namespace: default
type: Opaque
stringData:
  ## Specify SYS password here
  oracle_pwd: s3cret!
---
apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: xedb-sample
  namespace: default
spec:
  sid: XE
  edition: express
  adminPassword:
    secretName: xedb-admin-secret
  image:
    pullFrom: container-registry.oracle.com/database/express:latest
    prebuiltDB: true
  persistence:
    size: 50Gi
    storageClass: "standard"
    accessMode: "ReadWriteOnce"
  replicas: 1
