apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rest-api-db
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: rest-api-db
    apis.apps.tanzu.vmware.com/register-api: "EXPOSE_ENDPOINT"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_ssh_secret
    value: git-ssh
  source:
    git:
      url: "ssh://git@github.com:22/pivotal/acc-content.git"
      ref:
        branch: main
    subPath: rest-api-db
